languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon ECS Workshop"
theme = "learn"
uglyurls = false
# googleAnalytics = "UA-44634850-2"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "AWS Containers DA Team"
description = "Amazon ECS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
editURL = "https://github.com/aws-containers/ecsworkshop/edit/main/content/"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services]
  [services.youtube]
    privacyEnhanced = true

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-youtube'></i> Containers from the Couch"
url = "https://containersfromthecouch.com"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> EKS Workshop"
url = "https://eksworkshop.com"
weight = 7

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AWS Partner Workshops"
url = "https://awsworkshop.io"
weight = 8

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> ECS Cats and Dogs"
url = "https://ecs-cats-dogs.workshop.aws"
weight = 9

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
